// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvcvremlyomhskdppnsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Y3ZyZW1seW9taHNrZHBwbnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY0Njg3MjksImV4cCI6MjA5MjA0NDcyOX0.aO-hz3Ts3L7uaMMWI5g6BNU6zg1M5jsj9wnaTYciS44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});